apiVersion: v1
kind: Service
metadata:
  name: engligo-service
  labels:
    app: engligo
spec:
  type: LoadBalancer
  selector:
    app: engligo
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP